name: coore
description: "A Flutter package built for simplifying development process"
version: 0.0.22
homepage: null

environment:
  sdk: ^3.7.0
  flutter: ">=1.17.0"

dependencies:
  bloc: any
  cached_network_image: ^3.4.1
  dio: ^5.8.0+1
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_bloc: ^9.0.0
  flutter_dotenv: ^5.2.1
  flutter_secure_storage: ^9.2.4
  flutter_svg: ^2.0.17
  fpdart: ^1.1.1
  freezed_annotation: ^3.0.0
  gap: ^3.0.1
  get_it: ^8.0.3
  go_router: ^14.8.1
  hive_ce: ^2.10.1
  hive_ce_flutter: ^2.2.0
  internet_connection_checker_plus: ^2.7.0
  intl: ^0.19.0
  json_annotation: ^4.9.0
  logger: ^2.5.0
  path: any
  path_provider: ^2.1.5
  shimmer: ^3.0.0
  skeletonizer: ^1.4.3
dev_dependencies:
  build_runner: ^2.4.15
  custom_lint: ^0.7.5
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  freezed: ^3.0.2
  freezed_lint: ^0.0.9
  hive_ce_generator: ^1.8.2
  json_serializable: ^6.9.4

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter packages.
flutter:
  assets:
    - assets/images/image_placeholder.svg
# To add assets to your package, add an assets section, like this:
# assets:
#   - images/a_dot_burr.jpeg
#   - images/a_dot_ham.jpeg
#
# For details regarding assets in packages, see
# https://flutter.dev/to/asset-from-package
#
# An image asset can refer to one or more resolution-specific "variants", see
# https://flutter.dev/to/resolution-aware-images
# To add custom fonts to your package, add a fonts section here,
# in this "flutter" section. Each entry in this list should have a
# "family" key with the font family name, and a "fonts" key with a
# list giving the asset and other descriptors for the font. For
# example:
# fonts:
#   - family: Schyler
#     fonts:
#       - asset: fonts/Schyler-Regular.ttf
#       - asset: fonts/Schyler-Italic.ttf
#         style: italic
#   - family: Trajan Pro
#     fonts:
#       - asset: fonts/TrajanPro.ttf
#       - asset: fonts/TrajanPro_Bold.ttf
#         weight: 700
#
# For details regarding fonts in packages, see
# https://flutter.dev/to/font-from-package
