name: coore
description: "A Flutter package built for simplifying development process"
version: 1.0.2
homepage: null

environment:
  sdk: ^3.10.0
  flutter: ">=1.17.0"

dependencies:
  async: ^2.11.0
  bloc: any
  cached_network_image: ^3.4.1
  carousel_slider: ^5.1.1
  cookie_jar: ^4.0.8
  device_info_plus: ^12.2.0
  dio: ^5.8.0+1
  dio_cache_interceptor: ^4.0.3
  dio_cookie_manager: ^3.2.0
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_dotenv: ^6.0.0
  flutter_secure_storage: ^9.2.4
  flutter_svg: ^2.2.0
  fpdart: ^1.1.1
  freezed_annotation: ^3.1.0
  gap: ^3.0.1
  get_it: ^9.0.5
  go_router: ^17.0.0
  hive_ce: ^2.11.3
  hive_ce_flutter: ^2.3.1
  internet_connection_checker_plus: ^2.7.2
  intl: ^0.20.2
  json_annotation: ^4.9.0
  logger: ^2.6.1
  mutex: ^3.1.0
  package_info_plus: ^9.0.0
  path: any
  path_provider: ^2.1.5
  pinput: ^6.0.0
  easy_refresh: ^3.4.0
  readmore: ^3.0.0
  shimmer: ^3.0.0
  skeletonizer: ^2.1.0+1
  talker_bloc_logger: ^5.0.1
  typed_form_fields: ^1.3.1
  uuid: ^4.5.1
dev_dependencies:
  build_runner: ^2.6.0
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  freezed: ^3.2.0
  freezed_lint: ^0.0.10
  hive_ce_generator: ^1.9.3
  json_serializable: ^6.10.0
  mockito: ^5.4.4

executables:
  # For information on the generic Dart part of this file, see the
  # following page: https://dart.dev/tools/pub/pubspec
  # The following section is specific to Flutter packages.
  m2e:

flutter: null
# To add assets to your package, add an assets section, like this:
# assets:
#   - images/a_dot_burr.jpeg
#   - images/a_dot_ham.jpeg
#
# For details regarding assets in packages, see
# https://flutter.dev/to/asset-from-package
#
# An image asset can refer to one or more resolution-specific "variants", see
# https://flutter.dev/to/resolution-aware-images
# To add custom fonts to your package, add a fonts section here,
# in this "flutter" section. Each entry in this list should have a
# "family" key with the font family name, and a "fonts" key with a
# list giving the asset and other descriptors for the font. For
# example:
# fonts:
#   - family: Schyler
#     fonts:
#       - asset: fonts/Schyler-Regular.ttf
#       - asset: fonts/Schyler-Italic.ttf
#         style: italic
#   - family: Trajan Pro
#     fonts:
#       - asset: fonts/TrajanPro.ttf
#       - asset: fonts/TrajanPro_Bold.ttf
#         weight: 700
#
# For details regarding fonts in packages, see
# https://flutter.dev/to/font-from-package
